### ISSUE TITLE
Not able to run it

### ISSUE THREAD

**Issue by badis** [vaskoz/coffee-shop#3]
Would you please put some code showing how to compile, run and test this project with few scenarios if any.

I am getting this error: `main.go:28: Bad COFFEE_SHOP_CLOSE_TIME`

**Comment by badis** [comment]
It looks like there are few environment variables i should define. 
is it possible to refactor code to read them from a  `.env` file with demo values.

**Comment by vaskoz** [comment]
@badis I made updates to the program to make it more user-friendly and added more docs to the README. Thanks for filing the issue to remind me to look at this again. I hope this helps.

**Comment by badis** [comment]
@vaskoz I am new to GO and I was interested to take a look at few programs to familiarize myself with it. thank you very much for the quick updates :+1:
